#! /bin/sh

### BEGIN INIT INFO
# Provides:          lidar
# Required-Start:    $local_fs $remote_fs
# Required-Stop:
# X-Start-Before:    rmnologin
# Default-Start:     2 3 4 5
# Default-Stop:
# Short-Description: Provide limited super user privileges to specific users
# Description: Provide limited super user privileges to specific users.
### END INIT INFO
#
# Setup steps:
#	1. in /etc/init.d run:  ln -s /home/pi/GitHub/lidar18/startup/lidar
#	2. sudo insserv lidar
#	3. sudo systemctl enable lidar
#	4. sudo systemctl start lidar
#
# To Start/Stop the app
#	sudo systemctl start lidar
#
#	sudo systemctl stop lidar
##########################################################
#
#	kill `ps -def | grep LidarAlign60 | grep python | awk '{print $2}'`

. /lib/lsb/init-functions

set -e

case "$1" in
  start)
    cd /home/pi/GitHub/lidar18/ThisWorks; python LidarAlign60.py 10.10.73.2 &
	;;
  stop|reload|restart|force-reload|status)
	kill `ps -def | grep LidarAlignWithEquation60 | grep python | awk '{print $2}'`
	;;
  *)
	echo "Usage: $N {start|stop|restart|force-reload|status}" >&2
	exit 1
	;;
esac

exit 0
